PBI 7-8 People In Class
uasoft-indonesia/badaso-lms-module pull request #14
Opened 2022-03-01 13:30 UTC by IlmaMannix

2022-03-01 13:40 UTC, nofamex requested changes
kindly checked previously existing file on the staging branch

2022-03-01 13:40 UTC, nofamex commented on .github/workflows/sonarqube.yml
> +          SONAR_HOST_URL: "http://35.224.113.103:9000"
please do not commit this again, its already exist by default on any branch

2022-03-01 13:40 UTC, nofamex commented on sonar-project.properties
> +sonar.sources=src/
also remove this, its already exist

2022-03-01 13:40 UTC, nofamex commented on src/Commands/BadasoLMSSetup.php
>  }
please pull the latest from staging

2022-03-01 13:40 UTC, Zsaschz commented on tests/Feature/PeopleInClassTest.php
> +        $this->assertEmpty($response);
roses are red violet are blue,
this should be $response->assertSuccesfull() uwu

2022-03-01 13:40 UTC, AldiNFitrah approved these changes
LGTM!

2022-03-01 13:40 UTC, AldiNFitrah commented on src/Controllers/LMSController.php
> +}
I personally prefer the old version, but it's okay

2022-03-01 13:47 UTC, FXDROS commented on src/BadasoLMSModule.php
> -
Please pull from the `staging` branch

2022-03-01 13:49 UTC, FXDROS commented on src/Facades/BadasoLMSModule.php
> +}
Please pull the latest from the `staging` branch

2022-03-01 13:49 UTC, FXDROS commented on src/Providers/BadasoLMSModuleProvider.php
> +}
Please pull the latest from the `staging` branch

2022-03-01 13:53 UTC, darren-ngoh commented on src/Providers/BadasoLMSModuleProvider.php
> +}
Please pull the latest from the staging branch

2022-03-01 13:53 UTC, darren-ngoh commented on src/Seeder/BadasoLMSModuleSeeder.php
> +}
Please pull the latest from the staging branch

2022-03-01 14:13 UTC, Zsaschz commented
please make this pr WIP if you are still going to work on it

2022-03-13 13:34 UTC, nofamex approved these changes

2022-03-13 13:47 UTC, AldiNFitrah approved these changes
LGTM already, thanks!

2022-03-13 14:19 UTC, merged